# Commerce module for ACP-inspired e-commerce agent
from .catalog import (
    PRODUCTS,
    list_products,
    get_product_by_id,
    search_products,
    get_available_categories,
    get_available_colors,
)
from .orders import (
    create_order,
    get_order,
    get_last_order,
    get_all_orders,
    get_order_summary,
    cancel_order,
    ORDERS,
)
from .cart import (
    get_cart,
    add_to_cart,
    update_cart_item,
    remove_from_cart,
    clear_cart,
    get_cart_total,
    cart_to_line_items,
    create_checkout_session,
    get_checkout_session,
    update_checkout_session,
    CARTS,
    CHECKOUT_SESSIONS,
)

# ACP-aligned Pydantic models
from .models import (
    Product,
    ProductListResponse,
    CartItem,
    Cart,
    LineItem,
    Item,
    Total,
    TotalType,
    CheckoutSession,
    CheckoutStatus,
    FulfillmentOption,
    FulfillmentType,
    Address,
    Buyer,
    Order,
    OrderDetail,
    OrderStatus,
    OrderAnalytics,
    ErrorResponse,
    Message,
    MessageType,
    PaymentProvider,
    PaymentData,
    AddToCartRequest,
    UpdateCartItemRequest,
    CreateCheckoutRequest,
    UpdateCheckoutRequest,
    CompleteCheckoutRequest,
    CartUpdateMessage,
    OrderCreatedMessage,
)

__all__ = [
    # Catalog
    "PRODUCTS",
    "list_products",
    "get_product_by_id",
    "search_products",
    "get_available_categories",
    "get_available_colors",
    # Orders
    "create_order",
    "get_order",
    "get_last_order",
    "get_all_orders",
    "get_order_summary",
    "cancel_order",
    "ORDERS",
    # Cart
    "get_cart",
    "add_to_cart",
    "update_cart_item",
    "remove_from_cart",
    "clear_cart",
    "get_cart_total",
    "cart_to_line_items",
    "create_checkout_session",
    "get_checkout_session",
    "update_checkout_session",
    "CARTS",
    "CHECKOUT_SESSIONS",
    # Models
    "Product",
    "ProductListResponse",
    "CartItem",
    "Cart",
    "LineItem",
    "Item",
    "Total",
    "TotalType",
    "CheckoutSession",
    "CheckoutStatus",
    "FulfillmentOption",
    "FulfillmentType",
    "Address",
    "Buyer",
    "Order",
    "OrderDetail",
    "OrderStatus",
    "OrderAnalytics",
    "ErrorResponse",
    "Message",
    "MessageType",
    "PaymentProvider",
    "PaymentData",
    "AddToCartRequest",
    "UpdateCartItemRequest",
    "CreateCheckoutRequest",
    "UpdateCheckoutRequest",
    "CompleteCheckoutRequest",
    "CartUpdateMessage",
    "OrderCreatedMessage",
]
